name: Auto_Update_Deco
on:
  schedule:
    - cron: '0 20 * * *' # 北京时间凌晨 4:00
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests base58
      - name: Run update
        run: python update_deco.py
      - name: Commit and Push
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "DecoBot"
          git add .
          git commit -m "Update 50 sites and B58" || exit 0
          git push
