name: Auto_Update_Deco
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须有写入权限
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install requests base58
      - name: Run script
        run: python update_deco.py
      - name: Push
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "DecoBot"
          git add deco.json deco_b58.txt
          git commit -m "Refresh 50 sites" || exit 0
          git push
