name: Daily_Update
on:
  schedule:
    - cron: '0 20 * * *' # 这里的 20:00 UTC 就是北京时间凌晨 04:00
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Update
        run: |
          pip install requests
          python update_deco.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deco.json
          git commit -m "Auto Update" || exit 0
          git push
